domain_path: C:\Users\kartg\Desktop\2025_FPGA\hw4\workspace\platform\export\platform\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
